# Generated by Django 5.0.6 on 2024-05-27 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='الصورة')),
                ('profile_type', models.CharField(blank=True, choices=[('MG', 'Manager'), ('FI', 'Finan'), ('AUD', 'Auditor'), ('RES', 'Researcher')], max_length=3, null=True, verbose_name='الصلاحية')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='معلومات إضافية')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hquarter_profiles', to='locations.hquarter', verbose_name='الأمانة')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality_profiles', to='locations.locality', verbose_name='المحلية')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_profiles', to='locations.state', verbose_name='الولاية')),
                ('unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unity_profiles', to='locations.unity', verbose_name='الوحدة الإدارية')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'ordering': ['created'],
            },
        ),
    ]
