# Generated by Django 5.0.6 on 2024-05-30 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='')),
                ('slug', models.SlugField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'العلاوات',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='')),
                ('slug', models.SlugField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'القطاعات',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='dgree',
            name='bonus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_dgrees', to='employees.bonus', verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dgree',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_dgrees', to='employees.range', verbose_name=''),
        ),
    ]
