# Generated by Django 5.0.6 on 2024-06-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_bonus_range_dgree_bonus_alter_dgree_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgree',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
    ]
