# Generated by Django 5.0.6 on 2024-07-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_dgree_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgree',
            name='range',
        ),
        migrations.AddField(
            model_name='dgree',
            name='section',
            field=models.CharField(default=1, max_length=20, verbose_name='القطاع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dgree',
            name='bonus',
            field=models.CharField(choices=[('1', 'الأول'), ('2', 'الثانى'), ('3', 'الثالث'), ('4', 'الرابع'), ('5', 'الخامس'), ('6', 'السادس'), ('7', 'السابع'), ('8', 'الثامن'), ('9', 'التاسع')], max_length=2, verbose_name='العلاوة'),
        ),
    ]
