# Generated by Django 5.0.6 on 2024-07-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_dgree_range_dgree_section_alter_dgree_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgree',
            name='begin_date',
            field=models.DateField(blank=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='dgree',
            name='base_salary',
            field=models.FloatField(verbose_name='المرتب الاساسى'),
        ),
        migrations.AlterField(
            model_name='dgree',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='الدرجة'),
        ),
    ]
