# Generated by Django 5.0.6 on 2024-07-04 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_dgree_begin_date_alter_dgree_base_salary_and_more'),
        ('locations', '0004_alter_city_locality_alter_city_name_alter_city_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.IntegerField(unique=True, verbose_name='الرقم الوظيفى')),
                ('name', models.CharField(max_length=50, verbose_name='الأسم')),
                ('national_no', models.IntegerField(unique=True, verbose_name='الرقم الوطنى')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='الصورة')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('maritial_status', models.CharField(choices=[('MR', 'Married'), ('SN', 'Single'), ('DV', 'Divorced'), ('WD', 'Widow')], max_length=2, verbose_name='الحالة الإجتماعية')),
                ('wives_no', models.IntegerField(verbose_name='عدد الزوجات')),
                ('sons_no', models.IntegerField(verbose_name='عدد الإبناء')),
                ('education', models.CharField(choices=[('PR', 'بروفيسور'), ('DR', 'دكتوراة'), ('MS', 'ماجستير'), ('BS', 'بكلاريوس'), ('DP', 'دبلوم'), ('ثانوى', 'Secondary'), ('WC', 'دون شهادة')], max_length=5, verbose_name='المستوى التعليمى')),
                ('employee_type', models.CharField(choices=[('EM', 'موظف'), ('WK', 'عامل')], max_length=5, verbose_name='نوع الوظيفة')),
                ('slug', models.SlugField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_employees', to='locations.city', verbose_name='المدينة')),
                ('current_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locality_current', to='locations.locality', verbose_name='المحلية الحالية')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_current', to='locations.state', verbose_name='الولاية الحالية')),
                ('current_unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unity_current', to='locations.unity', verbose_name='الوحدة الحالية')),
                ('dgree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgree_employees', to='employees.dgree', verbose_name='الدرجة الوظيفية')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_employees', to='locations.locality', verbose_name='المحلية')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_employees', to='locations.state', verbose_name='الولاية')),
                ('unity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unity_employees', to='locations.unity', verbose_name='الوحدة الأدارية')),
            ],
            options={
                'verbose_name_plural': 'القوى العاملة',
                'ordering': ['created'],
            },
        ),
    ]
