# Generated by Django 5.0.6 on 2024-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgree',
            name='monthly_add',
            field=models.FloatField(blank=True, null=True, verbose_name='المنحة الشهرية'),
        ),
        migrations.AlterField(
            model_name='dgree',
            name='bonus',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], max_length=2, verbose_name='العلاوة'),
        ),
    ]
