# Generated by Django 5.0.6 on 2024-07-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_dgree_monthly_add_alter_dgree_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgree',
            name='yearly_add',
            field=models.FloatField(blank=True, null=True, verbose_name='المنحة السنوية'),
        ),
    ]
