# Generated by Django 5.0.6 on 2024-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_dgree_yearly_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgree',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التعريف'),
        ),
    ]
