# Generated by Django 5.0.6 on 2024-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_dgree_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgree',
            name='emp_type',
            field=models.CharField(choices=[('emp', 'موظف'), ('wk', 'عامل')], default='em', max_length=3, verbose_name='نوع الوظيفة'),
            preserve_default=False,
        ),
    ]
