# Generated by Django 5.0.6 on 2024-07-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='documents',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
