# Generated by Django 5.0.6 on 2024-07-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employee_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
