# Generated by Django 5.0.6 on 2024-08-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_image'),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='current_locality',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='current_unity',
        ),
        migrations.AddField(
            model_name='employee',
            name='hquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hquarter_emps', to='offices.hquarter', verbose_name='الولاية الحالية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_emps', to='offices.office', verbose_name='المكتب'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_emps', to='offices.sector', verbose_name='القطاع'),
        ),
    ]
