# Generated by Django 5.0.6 on 2024-09-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_employee_current_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
    ]
