# Generated by Django 5.0.6 on 2024-09-19 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_employee_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='document',
            name='serial',
        ),
    ]
