# Generated by Django 5.1.1 on 2024-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_rename_img_document_image_remove_document_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(upload_to='images/', verbose_name=''),
        ),
    ]
