# Generated by Django 5.1.1 on 2024-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.CharField(choices=[('ML', 'قسيمة زواج'), ('BD', 'شهادة ميلاد'), ('CB', 'عقيقة'), ('QL', 'مؤهل'), ('ID', 'ورقة ثبوتية')], default='', max_length=2, verbose_name=''),
            preserve_default=False,
        ),
    ]
