# Generated by Django 5.1.1 on 2024-10-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_document_code_document_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
