# Generated by Django 5.0.6 on 2024-06-10 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='top_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning_plannings', to='departments.planning', verbose_name='الأدارة العليا'),
        ),
    ]
