# Generated by Django 5.0.6 on 2024-06-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['created'], 'verbose_name_plural': 'الإدارات'},
        ),
        migrations.AlterField(
            model_name='department',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_related', to='departments.department', verbose_name='الأدارة العليا'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='الإدارة'),
        ),
    ]
