# Generated by Django 5.0.6 on 2024-07-04 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_options_alter_department_management_and_more'),
        ('employees', '0006_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='department',
            name='object_id',
        ),
        migrations.AddField(
            model_name='department',
            name='min_dgree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dgree_departmants', to='employees.dgree', verbose_name='الدرجة المحددة'),
            preserve_default=False,
        ),
    ]
