# Generated by Django 5.0.6 on 2024-08-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_remove_department_content_type_and_more'),
        ('employees', '0015_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_related', to='departments.department', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='min_dgree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dgree_departmants', to='employees.dgree', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name=''),
        ),
    ]
