# Generated by Django 5.0.6 on 2024-08-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_alter_department_management_and_more'),
        ('employees', '0015_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='min_dgree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgree_departmants', to='employees.dgree', verbose_name=''),
        ),
    ]
