# Generated by Django 5.0.6 on 2024-08-09 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_alter_department_min_dgree'),
        ('employees', '0015_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_related', to='departments.department', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='min_dgree',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dgree_departmants', to='employees.dgree', verbose_name=''),
            preserve_default=False,
        ),
    ]
