# Generated by Django 5.0.6 on 2024-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_alter_department_management_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='')),
                ('slug', models.SlugField(editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'الإدارات',
                'ordering': ['created'],
            },
        ),
    ]
