# Generated by Django 5.0.6 on 2024-06-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='الولاية'),
        ),
    ]
