# Generated by Django 5.0.6 on 2024-07-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hquarter',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='الرئاسة'),
        ),
        migrations.AlterField(
            model_name='hquarter',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_hquarters', to='locations.state', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='المحلية'),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_localities', to='locations.state', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_unities', to='locations.locality', verbose_name='المحلية'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='الوحدة الإدارية'),
        ),
        migrations.AlterField(
            model_name='unity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_unities', to='locations.state', verbose_name='الولاية'),
        ),
    ]
