# Generated by Django 5.0.6 on 2024-08-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_city_locality_alter_city_name_alter_city_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
    ]
