# Generated by Django 5.0.6 on 2024-08-07 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_localities', to='locations.state', verbose_name=''),
        ),
    ]
