# Generated by Django 5.0.6 on 2024-08-07 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_locality_name_alter_locality_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hquarter',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='hquarter',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_hquarters', to='locations.state', verbose_name=''),
        ),
    ]
