# Generated by Django 5.0.6 on 2024-08-07 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_hquarter_name_alter_hquarter_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_unities', to='locations.locality', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='unity',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='unity',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_unities', to='locations.state', verbose_name=''),
        ),
    ]
