# Generated by Django 5.0.6 on 2024-08-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_unity_locality_alter_unity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality_cities', to='locations.locality', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_cities', to='locations.state', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='city',
            name='unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unity_cities', to='locations.unity', verbose_name=''),
        ),
    ]
